# Generated by Django 3.2.10 on 2025-02-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0002_studentadmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiblingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('current_school', models.CharField(max_length=200)),
                ('current_class', models.CharField(max_length=50)),
                ('admission_form_collected', models.BooleanField(default=False)),
                ('school_leaving_certificate_collected', models.BooleanField(default=False)),
                ('bonafide_certificate_collected', models.BooleanField(default=False)),
                ('birth_certificate_collected', models.BooleanField(default=False)),
                ('caste_certificate_collected', models.BooleanField(default=False)),
                ('ration_card_collected', models.BooleanField(default=False)),
                ('student_adhar_collected', models.BooleanField(default=False)),
                ('father_adhar_collected', models.BooleanField(default=False)),
                ('mother_adhar_collected', models.BooleanField(default=False)),
                ('admission_form_remarks', models.TextField(default='Partial')),
                ('school_leaving_certificate_remarks', models.TextField(default='Partial')),
                ('bonafide_certificate_remarks', models.TextField(default='Partial')),
                ('birth_certificate_remarks', models.TextField(default='Partial')),
                ('caste_certificate_remarks', models.TextField(default='Partial')),
                ('ration_card_remarks', models.TextField(default='Partial')),
                ('student_adhar_remarks', models.TextField(default='Partial')),
                ('father_adhar_remarks', models.TextField(default='Partial')),
                ('mother_adhar_remarks', models.TextField(default='Partial')),
            ],
        ),
    ]
