# Generated by Django 3.2.10 on 2025-02-11 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0003_siblingdocument'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiblingDocument',
        ),
    ]
