# Generated by Django 3.2.10 on 2025-02-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0004_delete_siblingdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiblingDocumentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(blank=True, max_length=100, null=True)),
                ('age1', models.PositiveIntegerField(blank=True, null=True)),
                ('gender1', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('school1', models.CharField(blank=True, max_length=100, null=True)),
                ('class1', models.CharField(blank=True, max_length=100, null=True)),
                ('name2', models.CharField(blank=True, max_length=100, null=True)),
                ('age2', models.PositiveIntegerField(blank=True, null=True)),
                ('gender2', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('school2', models.CharField(blank=True, max_length=100, null=True)),
                ('class2', models.CharField(blank=True, max_length=100, null=True)),
                ('name3', models.CharField(blank=True, max_length=100, null=True)),
                ('age3', models.PositiveIntegerField(blank=True, null=True)),
                ('gender3', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('school3', models.CharField(blank=True, max_length=100, null=True)),
                ('class3', models.CharField(blank=True, max_length=100, null=True)),
                ('name4', models.CharField(blank=True, max_length=100, null=True)),
                ('age4', models.PositiveIntegerField(blank=True, null=True)),
                ('gender4', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('school4', models.CharField(blank=True, max_length=100, null=True)),
                ('class4', models.CharField(blank=True, max_length=100, null=True)),
                ('name5', models.CharField(blank=True, max_length=100, null=True)),
                ('age5', models.PositiveIntegerField(blank=True, null=True)),
                ('gender5', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('school5', models.CharField(blank=True, max_length=100, null=True)),
                ('class5', models.CharField(blank=True, max_length=100, null=True)),
                ('admission_form', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('partial', 'Partial'), ('na', 'N/A')], max_length=10, null=True)),
                ('admission_form_remarks', models.TextField(blank=True, null=True)),
                ('school_leaving_certificate', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('partial', 'Partial'), ('na', 'N/A')], max_length=10, null=True)),
                ('school_leaving_certificate_remarks', models.TextField(blank=True, null=True)),
                ('bonafide_certificate', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('partial', 'Partial'), ('na', 'N/A')], max_length=10, null=True)),
                ('bonafide_certificate_remarks', models.TextField(blank=True, null=True)),
                ('birth_certificate', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('partial', 'Partial'), ('na', 'N/A')], max_length=10, null=True)),
                ('birth_certificate_remarks', models.TextField(blank=True, null=True)),
                ('caste_certificate', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('partial', 'Partial'), ('na', 'N/A')], max_length=10, null=True)),
                ('caste_certificate_remarks', models.TextField(blank=True, null=True)),
                ('all_documents', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('partial', 'Partial'), ('na', 'N/A')], max_length=10, null=True)),
                ('all_documents_remarks', models.TextField(blank=True, null=True)),
                ('ration_card', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('partial', 'Partial'), ('na', 'N/A')], max_length=10, null=True)),
                ('ration_card_remarks', models.TextField(blank=True, null=True)),
                ('student_adhar_certificate', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('partial', 'Partial'), ('na', 'N/A')], max_length=10, null=True)),
                ('student_adhar_certificate_remarks', models.TextField(blank=True, null=True)),
                ('father_adhar_certificate', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('partial', 'Partial'), ('na', 'N/A')], max_length=10, null=True)),
                ('father_adhar_certificate_remarks', models.TextField(blank=True, null=True)),
                ('mother_adhar_certificate', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('partial', 'Partial'), ('na', 'N/A')], max_length=10, null=True)),
                ('mother_adhar_certificate_remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
