# Generated by Django 3.2.10 on 2025-02-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0005_siblingdocumentsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siblingdocumentsubmission',
            name='age1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siblingdocumentsubmission',
            name='age2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siblingdocumentsubmission',
            name='age3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siblingdocumentsubmission',
            name='age4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siblingdocumentsubmission',
            name='age5',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
