# Generated by Django 3.2.10 on 2025-02-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0006_auto_20250211_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siblingdocumentsubmission',
            name='age1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='siblingdocumentsubmission',
            name='age2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='siblingdocumentsubmission',
            name='age3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='siblingdocumentsubmission',
            name='age4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='siblingdocumentsubmission',
            name='age5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
