# Generated by Django 3.2.10 on 2025-02-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0007_auto_20250211_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_available', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('bus_no', models.CharField(choices=[('AP39UF0940', 'AP39UF0940'), ('AP39UF0930', 'AP39UF0930')], max_length=10)),
                ('driver_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('route', models.CharField(choices=[('R12', 'R12'), ('R13', 'R13'), ('R14', 'R14')], max_length=3)),
                ('stoppage', models.CharField(choices=[('Stop1', 'Stop 1'), ('Stop2', 'Stop 2'), ('Stop3', 'Stop 3')], max_length=10)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pick_up', models.CharField(max_length=100)),
                ('drop_off', models.CharField(max_length=100)),
                ('fee_category', models.CharField(choices=[('staffWard', 'STAFF WARD'), ('staffWard2', 'STAFF WARD2')], max_length=20)),
                ('fee_type', models.CharField(choices=[('monthly', 'MONTHLY'), ('quarterly', 'QUARTERLY')], max_length=20)),
            ],
        ),
    ]
