# Generated by Django 3.2.10 on 2025-02-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0008_transportinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportinformation',
            name='bus_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='transportinformation',
            name='fee_category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transportinformation',
            name='fee_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transportinformation',
            name='route',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='transportinformation',
            name='stoppage',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='transportinformation',
            name='transport_available',
            field=models.CharField(default='no', max_length=3),
        ),
    ]
