# Generated by Django 3.2.10 on 2025-02-12 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0010_delete_studentadmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentadmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enqno', models.CharField(default='', max_length=50)),
                ('session', models.CharField(default='', max_length=50)),
                ('registrationno', models.CharField(default='', max_length=50)),
                ('classs', models.CharField(default='', max_length=20)),
                ('section', models.CharField(default='', max_length=10)),
                ('srnno', models.CharField(default='', max_length=50)),
                ('formno', models.CharField(default='', max_length=50)),
                ('studenttype', models.CharField(default='', max_length=50)),
                ('studentname', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(default='', max_length=10)),
                ('dateofbirth', models.DateField()),
                ('aadharno', models.CharField(default='', max_length=12)),
                ('house', models.CharField(default='', max_length=50)),
                ('stream', models.CharField(default='', max_length=50)),
                ('emil', models.EmailField(default='', max_length=254)),
                ('previousyearattendance', models.TextField(default='')),
                ('mothertongue', models.CharField(default='', max_length=50)),
                ('adoptedchild', models.CharField(default='', max_length=10)),
                ('minority', models.CharField(default='', max_length=50)),
                ('specify', models.TextField(default='')),
                ('nationality', models.CharField(default='', max_length=50)),
                ('mediumofinstruction', models.CharField(default='', max_length=50)),
                ('castecategory', models.CharField(default='', max_length=50)),
                ('optionalsubject', models.TextField(default='')),
                ('offeredsubject', models.TextField(default='')),
                ('penno', models.CharField(default='', max_length=50)),
                ('bloodgroup', models.CharField(default='', max_length=5)),
                ('leftvision', models.CharField(default='', max_length=10)),
                ('rightvision', models.CharField(default='', max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('weight1', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('height1', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('disability', models.CharField(default='', max_length=50)),
                ('sportsactivity', models.TextField(default='')),
                ('admissiondate', models.DateField()),
                ('bankname', models.CharField(default='', max_length=100)),
                ('branchname', models.CharField(default='', max_length=100)),
                ('accountno', models.CharField(default='', max_length=50)),
                ('ifsccode', models.CharField(default='', max_length=11)),
            ],
            options={
                'db_table': 'studentadmission',
            },
        ),
        migrations.CreateModel(
            name='Previousschooling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolnameandaddress', models.CharField(max_length=100)),
                ('classname', models.CharField(max_length=100)),
                ('session', models.CharField(max_length=100)),
                ('curriculum', models.CharField(max_length=50)),
                ('subjects', models.CharField(max_length=50)),
                ('stdid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workshifts1', to='ERP.studentadmission')),
            ],
        ),
        migrations.CreateModel(
            name='EducationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=100)),
                ('institute_name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('qualification1', models.CharField(blank=True, max_length=50, null=True)),
                ('specialization1', models.CharField(blank=True, max_length=100, null=True)),
                ('institute_name1', models.CharField(blank=True, max_length=100, null=True)),
                ('state1', models.CharField(blank=True, max_length=50, null=True)),
                ('city1', models.CharField(blank=True, max_length=50, null=True)),
                ('qualification2', models.CharField(blank=True, max_length=50, null=True)),
                ('specialization2', models.CharField(blank=True, max_length=100, null=True)),
                ('institute_name2', models.CharField(blank=True, max_length=100, null=True)),
                ('state2', models.CharField(blank=True, max_length=50, null=True)),
                ('city2', models.CharField(blank=True, max_length=50, null=True)),
                ('stdid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workshifts', to='ERP.studentadmission')),
            ],
        ),
        migrations.AddField(
            model_name='familydetails',
            name='stdid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workshifts2', to='ERP.studentadmission'),
        ),
        migrations.AddField(
            model_name='siblingdocumentsubmission',
            name='stdid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workshifts3', to='ERP.studentadmission'),
        ),
        migrations.AddField(
            model_name='transportinformation',
            name='stdid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workshifts4', to='ERP.studentadmission'),
        ),
    ]
