# Generated by Django 3.2.10 on 2025-02-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0011_auto_20250212_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familydetails',
            name='father_annual_income',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='familydetails',
            name='guardian_annual_income',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='familydetails',
            name='mother_annual_income',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='dateofbirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='height',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='height1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='weight',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='weight1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='transportinformation',
            name='fee',
            field=models.CharField(default='', max_length=50),
        ),
    ]
