# Generated by Django 3.2.10 on 2025-02-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0012_auto_20250213_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentadmission',
            name='offeredsubject',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='optionalsubject',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
