# Generated by Django 3.2.10 on 2025-02-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0013_auto_20250213_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationdetail',
            name='city',
        ),
        migrations.RemoveField(
            model_name='educationdetail',
            name='city1',
        ),
        migrations.RemoveField(
            model_name='educationdetail',
            name='city2',
        ),
        migrations.RemoveField(
            model_name='educationdetail',
            name='institute_name',
        ),
        migrations.RemoveField(
            model_name='educationdetail',
            name='institute_name1',
        ),
        migrations.RemoveField(
            model_name='educationdetail',
            name='institute_name2',
        ),
        migrations.RemoveField(
            model_name='educationdetail',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='educationdetail',
            name='qualification1',
        ),
        migrations.RemoveField(
            model_name='educationdetail',
            name='qualification2',
        ),
        migrations.RemoveField(
            model_name='educationdetail',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='educationdetail',
            name='specialization1',
        ),
        migrations.RemoveField(
            model_name='educationdetail',
            name='specialization2',
        ),
        migrations.RemoveField(
            model_name='educationdetail',
            name='state',
        ),
        migrations.RemoveField(
            model_name='educationdetail',
            name='state1',
        ),
        migrations.RemoveField(
            model_name='educationdetail',
            name='state2',
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='cityf1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='cityf2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='cityf3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='cityf4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='cityf5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='cityg1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='cityg2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='cityg3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='cityg4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='cityg5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='citym1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='citym2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='citym3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='citym4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='citym5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='institute_namef1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='institute_namef2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='institute_namef3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='institute_namef4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='institute_namef5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='institute_nameg1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='institute_nameg2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='institute_nameg3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='institute_nameg4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='institute_nameg5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='institute_namem1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='institute_namem2',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='institute_namem3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='institute_namem4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='institute_namem5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='qualificationf1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='qualificationf2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='qualificationf3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='qualificationf4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='qualificationf5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='qualificationg1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='qualificationg2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='qualificationg3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='qualificationg4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='qualificationg5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='qualificationm1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='qualificationm2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='qualificationm3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='qualificationm4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='qualificationm5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='specializationf1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='specializationf2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='specializationf3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='specializationf4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='specializationf5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='specializationg1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='specializationg2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='specializationg3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='specializationg4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='specializationg5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='specializationm1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='specializationm2',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='specializationm3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='specializationm4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='specializationm5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='statef1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='statef2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='statef3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='statef4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='statef5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='stateg1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='stateg2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='stateg3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='stateg4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='stateg5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='statem1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='statem2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='statem3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='statem4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='statem5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
