# Generated by Django 3.2.10 on 2025-02-17 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0015_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationdetail',
            name='custid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customt1', to='ERP.customuser'),
        ),
        migrations.AddField(
            model_name='familydetails',
            name='custid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customsd1', to='ERP.customuser'),
        ),
        migrations.AddField(
            model_name='previousschooling',
            name='custid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom1', to='ERP.customuser'),
        ),
        migrations.AddField(
            model_name='siblingdocumentsubmission',
            name='custid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customfdf1', to='ERP.customuser'),
        ),
        migrations.AddField(
            model_name='studentadmission',
            name='custid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customss1', to='ERP.customuser'),
        ),
        migrations.AddField(
            model_name='transportinformation',
            name='custid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customd1', to='ERP.customuser'),
        ),
    ]
