# Generated by Django 3.2.10 on 2025-02-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0016_auto_20250217_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentadmission',
            name='profile_photo',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
