# Generated by Django 3.2.10 on 2025-02-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0018_alter_studentadmission_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_fee_structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_class', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
