# Generated by Django 3.2.10 on 2025-02-18 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0019_admin_fee_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classs', models.CharField(max_length=50)),
                ('original_amount', models.IntegerField()),
                ('part1', models.IntegerField()),
                ('part2', models.IntegerField()),
                ('part3', models.IntegerField()),
                ('stdid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeamount', to='ERP.studentadmission')),
            ],
        ),
    ]
