# Generated by Django 3.2.10 on 2025-02-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0020_amount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Amount',
            new_name='student_fee_Amount',
        ),
    ]
