# Generated by Django 3.2.10 on 2025-02-19 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0021_rename_amount_student_fee_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_fee_amount',
            name='custid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custoddmd1', to=settings.AUTH_USER_MODEL),
        ),
    ]
