# Generated by Django 3.2.10 on 2025-02-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0023_auto_20250219_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentadmission',
            name='admissiondate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
