# Generated by Django 3.2.10 on 2025-02-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0024_alter_studentadmission_admissiondate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_fee_amount',
            name='part1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student_fee_amount',
            name='part2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student_fee_amount',
            name='part3',
            field=models.IntegerField(default=0),
        ),
    ]
