# Generated by Django 3.2.10 on 2025-02-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0025_auto_20250220_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentadmission',
            name='address',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='studentadmission',
            name='mbno',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='house',
            field=models.CharField(default='', max_length=150),
        ),
    ]
