# Generated by Django 3.2.10 on 2025-02-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0027_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentadmission',
            name='mbno',
            field=models.CharField(default='', max_length=150),
        ),
    ]
