# Generated by Django 3.2.10 on 2025-02-22 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0028_alter_studentadmission_mbno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
