# Generated by Django 3.2.10 on 2025-02-24 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0030_classinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('fathername', models.CharField(max_length=100)),
                ('amount', models.IntegerField(default=0)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('admissionno', models.CharField(default='', max_length=100)),
                ('mobilenumber', models.IntegerField(default=0)),
                ('std_class', models.CharField(default='', max_length=100)),
                ('admission_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP.studentadmission')),
                ('custid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='ERP.student_fee_amount')),
            ],
        ),
    ]
