# Generated by Django 3.2.10 on 2025-02-24 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0031_studentpayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentpayment',
            old_name='amount',
            new_name='amount1',
        ),
    ]
