# Generated by Django 5.0.1 on 2025-03-10 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0033_assignedclass_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpayment',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='ERP.student_fee_amount'),
        ),
    ]
