# Generated by Django 5.0.1 on 2025-03-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0034_alter_studentpayment_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpayment',
            name='student',
            field=models.CharField(default='', max_length=100),
        ),
    ]
