# Generated by Django 5.0.1 on 2025-03-11 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0040_studentmarks_teacherid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentadmission',
            name='classs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workshifts', to='ERP.admin_fee_structure'),
        ),
    ]
