# Generated by Django 5.0.1 on 2025-03-11 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0042_alter_studentadmission_classs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentadmission',
            name='classs',
        ),
    ]
