# Generated by Django 5.0.1 on 2025-03-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0043_remove_studentadmission_classs'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentadmission',
            name='classs',
            field=models.CharField(default='', max_length=20),
        ),
    ]
