# Generated by Django 5.0.1 on 2025-03-11 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0044_studentadmission_classs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.class')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.class')),
                ('section_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.section')),
            ],
        ),
    ]
