# Generated by Django 5.0.1 on 2025-03-11 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0046_remove_subject_section_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_fee_structure',
            name='std_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.class'),
        ),
    ]
