# Generated by Django 5.0.1 on 2025-03-11 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0047_alter_admin_fee_structure_std_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_fee_structure',
            old_name='std_class',
            new_name='class_assigned',
        ),
    ]
