# Generated by Django 5.0.1 on 2025-03-11 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0048_rename_std_class_admin_fee_structure_class_assigned'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.class')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.section')),
            ],
        ),
    ]
