# Generated by Django 5.0.1 on 2025-03-11 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0049_studentfeerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentadmission',
            name='classs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.class'),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.section'),
        ),
    ]
