# Generated by Django 5.0.1 on 2025-03-12 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0052_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMarks1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.studentadmission')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.teacher')),
            ],
        ),
    ]
