# Generated by Django 5.0.1 on 2025-03-13 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0054_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedclass',
            name='class_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dffgtrytrytt', to='ERP.class'),
        ),
        migrations.AlterField(
            model_name='assignedclass',
            name='custid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigneddfdfdgdfgdfssscustomers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignedclass',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignffdddddsections', to='ERP.section'),
        ),
        migrations.AlterField(
            model_name='assignedclass',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignedfdegfregterclasses', to='ERP.teacher'),
        ),
    ]
