# Generated by Django 5.0.1 on 2025-03-15 04:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0055_alter_assignedclass_class_assigned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.studentadmission')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.assignedclass')),
            ],
        ),
    ]
