# Generated by Django 5.0.1 on 2025-03-15 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0057_alter_attendance_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='custid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
