# Generated by Django 5.0.1 on 2025-03-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0058_attendance_custid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('all', 'All')], default='all', max_length=10)),
                ('assigned_students', models.ManyToManyField(blank=True, related_name='student_events', to='ERP.studentadmission')),
                ('assigned_teachers', models.ManyToManyField(blank=True, related_name='teacher_events', to='ERP.teacher')),
            ],
        ),
    ]
