# Generated by Django 5.0.1 on 2025-03-15 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0060_remove_event_date_event_event_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
