# Generated by Django 5.0.1 on 2025-03-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0061_delete_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentadmission',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
