# Generated by Django 5.0.1 on 2025-03-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0062_studentadmission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationdetail',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='familydetails',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='previousschooling',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='siblingdocumentsubmission',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student_fee_amount',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transportinformation',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
