# Generated by Django 5.0.1 on 2025-03-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0063_educationdetail_status_familydetails_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
