# Generated by Django 5.0.1 on 2025-03-20 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0064_teacher_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('accountant', 'Accountant'), ('student', 'Student')], max_length=10)),
                ('studentid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentcredentials', to='ERP.studentadmission')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plain_credentials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('accountant', 'Accountant'), ('student', 'Student')], max_length=10)),
                ('teacherid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachercredentials', to='ERP.teacher')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plain_credentials1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
