# Generated by Django 3.2.10 on 2025-03-20 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0065_studentcredentials_teachercredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmarks1',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP.exam'),
        ),
    ]
