# Generated by Django 3.2.10 on 2025-03-24 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0070_alter_leaverequest_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='section_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP.section'),
        ),
    ]
