# Generated by Django 3.2.10 on 2025-03-26 06:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0073_extrasubjectmarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoScholasticGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1, unique=True)),
                ('grade_point', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReportCardSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_signature', models.CharField(max_length=100)),
                ('report_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.studentadmission')),
            ],
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.studentadmission')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplineGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.studentadmission')),
            ],
        ),
    ]
