# Generated by Django 3.2.10 on 2025-03-26 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0074_coscholasticgrade_disciplinegrade_remark_reportcardsignature'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectMarksDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pa', models.FloatField(default=0)),
                ('se', models.FloatField(default=0)),
                ('ma', models.FloatField(default=0)),
                ('nb', models.FloatField(default=0)),
                ('term', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.studentadmission')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.subject')),
            ],
        ),
    ]
