# Generated by Django 3.2.10 on 2025-03-26 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0075_subjectmarksdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentadmission',
            name='classs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP.class'),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP.section'),
        ),
    ]
