# Generated by Django 3.2.10 on 2025-03-28 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0077_circular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentadmission',
            name='admissiondate',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
