# Generated by Django 3.2.10 on 2025-03-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0078_alter_studentadmission_admissiondate'),
    ]

    operations = [
        migrations.AddField(
            model_name='circular',
            name='circular_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
