# Generated by Django 5.0.1 on 2025-04-03 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0079_circular_circular_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('accountant', 'Accountant'), ('student', 'Student')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studentcredentials',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('accountant', 'Accountant'), ('student', 'Student')], max_length=10),
        ),
        migrations.AlterField(
            model_name='teachercredentials',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('accountant', 'Accountant'), ('student', 'Student')], max_length=10),
        ),
        migrations.CreateModel(
            name='SchoolDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('principal_name', models.CharField(max_length=255)),
                ('established_year', models.PositiveIntegerField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('description', models.TextField()),
                ('custid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schools1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
