# Generated by Django 5.0.1 on 2025-04-03 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0080_alter_customuser_role_alter_studentcredentials_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='ERP.schooldetails'),
        ),
    ]
