# Generated by Django 5.0.1 on 2025-04-03 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0081_class_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_fee_structure',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adminfeestructure', to='ERP.schooldetails'),
        ),
        migrations.AddField(
            model_name='section',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='ERP.schooldetails'),
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='ERP.schooldetails'),
        ),
    ]
