# Generated by Django 5.0.1 on 2025-04-03 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0082_admin_fee_structure_school_section_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Teachers', to='ERP.schooldetails'),
        ),
    ]
