# Generated by Django 5.0.1 on 2025-04-03 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0083_teacher_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachercredentials',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacherpasswords', to='ERP.schooldetails'),
        ),
    ]
