# Generated by Django 5.0.1 on 2025-04-03 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0084_teachercredentials_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationdetail',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edu', to='ERP.schooldetails'),
        ),
        migrations.AddField(
            model_name='familydetails',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fds', to='ERP.schooldetails'),
        ),
        migrations.AddField(
            model_name='previousschooling',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prevs', to='ERP.schooldetails'),
        ),
        migrations.AddField(
            model_name='siblingdocumentsubmission',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='siblings', to='ERP.schooldetails'),
        ),
        migrations.AddField(
            model_name='student_fee_amount',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stdfee', to='ERP.schooldetails'),
        ),
        migrations.AddField(
            model_name='studentadmission',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stdadmission', to='ERP.schooldetails'),
        ),
        migrations.AddField(
            model_name='transportinformation',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transport', to='ERP.schooldetails'),
        ),
    ]
