# Generated by Django 5.0.1 on 2025-04-03 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0085_educationdetail_school_familydetails_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcredentials',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stdcredits', to='ERP.schooldetails'),
        ),
    ]
