# Generated by Django 5.0.1 on 2025-04-04 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0088_assignedclass_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmarks1',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stdmarks1', to='ERP.schooldetails'),
        ),
    ]
