# Generated by Django 5.0.1 on 2025-04-07 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0090_alter_class_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacherdashboardheading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='teachersubmenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('urls', models.CharField(max_length=200)),
                ('teacherid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.teacherdashboardheading')),
            ],
        ),
    ]
