# Generated by Django 5.0.1 on 2025-04-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0091_teacherdashboardheading_teachersubmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherdashboardheading',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
