# Generated by Django 5.0.1 on 2025-04-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0092_teacherdashboardheading_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersubmenu',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
