# Generated by Django 5.0.1 on 2025-04-07 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0093_teachersubmenu_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherdashboardheading',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP.schooldetails'),
        ),
        migrations.AddField(
            model_name='teachersubmenu',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP.schooldetails'),
        ),
    ]
