# Generated by Django 3.2.10 on 2025-04-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0095_event_galleryalbum_galleryimage_nonteachingstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('accountant', 'Accountant'), ('student', 'Student'), ('non_teaching_staff', 'Non-Teaching Staff')], max_length=30),
        ),
        migrations.AlterField(
            model_name='studentcredentials',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('accountant', 'Accountant'), ('student', 'Student'), ('non_teaching_staff', 'Non-Teaching Staff')], max_length=30),
        ),
        migrations.AlterField(
            model_name='teachercredentials',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('accountant', 'Accountant'), ('student', 'Student'), ('non_teaching_staff', 'Non-Teaching Staff')], max_length=30),
        ),
    ]
