# Generated by Django 3.2.10 on 2025-04-09 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0096_auto_20250409_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vechile_name', models.CharField(max_length=100)),
                ('vechile_number', models.CharField(max_length=100)),
                ('date_of_purchase', models.DateField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='ERP.schooldetails')),
            ],
        ),
    ]
