# Generated by Django 3.2.10 on 2025-04-09 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0098_auto_20250409_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_point', models.CharField(max_length=100)),
                ('end_point', models.CharField(max_length=100)),
                ('stops', models.TextField(help_text='Comma-separated list of stops')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.schooldetails')),
            ],
        ),
        migrations.AddField(
            model_name='transport',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERP.route'),
        ),
    ]
