# Generated by Django 3.2.10 on 2025-04-10 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0100_transportattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reported', models.DateField(auto_now_add=True)),
                ('issue_type', models.CharField(choices=[('Bus Delay', 'Bus Delay'), ('Safety Concern', 'Safety Concern'), ('Missed Pickup', 'Missed Pickup'), ('No Transport Service', 'No Transport Service'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.schooldetails')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.studentadmission')),
            ],
        ),
    ]
