# Generated by Django 3.2.10 on 2025-04-10 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0101_transportissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportissue',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP.transport'),
        ),
    ]
