# Generated by Django 5.0.1 on 2025-05-02 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0105_message_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='circular',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='circularlist', to='ERP.schooldetails'),
        ),
    ]
