# Generated by Django 3.2.10 on 2025-05-20 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0108_leadsource'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassPhoto',
        ),
    ]
