# Generated by Django 3.2.10 on 2025-05-20 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0111_delete_classphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='class_photos/')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.class')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.exam')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.schooldetails')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.section')),
            ],
        ),
    ]
