# Generated by Django 3.2.10 on 2025-05-20 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0112_classphoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeadSource',
        ),
    ]
