# Generated by Django 3.2.10 on 2025-05-20 06:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0114_delete_classphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ClassPhoto1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='class_photos/')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.class')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.exam')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.schooldetails')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.section')),
            ],
        ),
    ]
