# Generated by Django 3.2.10 on 2025-05-20 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0116_leadstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_class', models.CharField(max_length=50)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('referred_by', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('mother_qualification', models.CharField(blank=True, max_length=100)),
                ('mother_res_address', models.TextField(blank=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=100)),
                ('mother_official_address', models.TextField(blank=True)),
                ('mother_income', models.CharField(blank=True, max_length=100)),
                ('mother_email', models.EmailField(blank=True, max_length=254)),
                ('mother_mobile', models.CharField(blank=True, max_length=15)),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('father_qualification', models.CharField(blank=True, max_length=100)),
                ('father_res_address', models.TextField(blank=True)),
                ('father_occupation', models.CharField(blank=True, max_length=100)),
                ('father_official_address', models.TextField(blank=True)),
                ('father_income', models.CharField(blank=True, max_length=100)),
                ('father_email', models.EmailField(blank=True, max_length=254)),
                ('father_mobile', models.CharField(blank=True, max_length=15)),
                ('nationality', models.CharField(blank=True, max_length=50)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('aadhar_no', models.CharField(blank=True, max_length=20)),
                ('last_school_name', models.CharField(blank=True, max_length=200)),
                ('last_attended_class', models.CharField(blank=True, max_length=50)),
                ('last_school_affiliated_to', models.CharField(blank=True, max_length=200)),
                ('remark', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERP.leadstatus')),
            ],
        ),
    ]
