# Generated by Django 3.2.10 on 2025-05-20 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0118_auto_20250520_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP.schooldetails'),
        ),
        migrations.AddField(
            model_name='leadsource',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP.schooldetails'),
        ),
        migrations.AddField(
            model_name='leadstatus',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP.schooldetails'),
        ),
    ]
