# Generated by Django 3.2.10 on 2025-05-20 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0120_transportfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportfee',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP.schooldetails'),
        ),
    ]
