# Generated by Django 3.2.10 on 2025-05-21 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0121_transportfee_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportinformation',
            name='fee',
        ),
        migrations.AddField(
            model_name='transportinformation',
            name='fee1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP.transportfee'),
        ),
    ]
