# Generated by Django 3.2.10 on 2025-05-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0123_lead_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='profile',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/'),
        ),
    ]
