# Generated by Django 3.2.10 on 2025-05-24 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0124_teacher_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10)),
                ('period', models.CharField(choices=[('Period 1', 'Period 1'), ('Period 2', 'Period 2'), ('Period 3', 'Period 3'), ('Period 4', 'Period 4'), ('Period 5', 'Period 5'), ('Period 6', 'Period 6'), ('Period 7', 'Period 7'), ('Period 8', 'Period 8')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.class')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP.schooldetails')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.teacher')),
            ],
            options={
                'unique_together': {('class_name', 'section', 'weekday', 'period', 'school')},
            },
        ),
    ]
