"""IDPSERP1 URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from ERP import views

urlpatterns = [
   
    path('insert_student_admission/', views.insert_student_admission, name='insert_student_admission'),
    path('get_driver_details/', views.get_driver_details, name='get_driver_details'),
    path('student_list/', views.student_list, name='student_list'),
    path('std_edit/<int:id>/',views.std_edit,name="std_edit"),
    path('student_profile/<int:id>/',views.student_profile,name="student_profile"),
    path('update_student/<int:id>/',views.update_student,name="update_student"),
    path('update_student_profile/<int:id>/', views.update_student_profile, name="update_student_profile"),
    path('update_student_profile1/<int:id>/', views.update_student_profile1, name="update_student_profile1"),
    path('std_delete/<int:id>/',views.std_delete,name="std_delete"),
    path('user_login/', views.user_login, name="user_login"),
    path('user_logout/', views.user_logout, name='user_logout'),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('admin_login/',views.admin_login, name="admin_login"),
    path('admin_insert_fee/',views.admin_insert_fee, name="admin_insert_fee"),
    path('display_fee/',views.display_fee, name="display_fee"),
    path('student_fee_management/',views.student_fee_management, name="student_fee_management"),
    path('login_list/',views.login_list,name="login_list"),
    path('login_edit/<int:id>/',views.login_edit,name="login_edit"),
    path('update_login/<int:id>/',views.update_login,name="update_login"),
    path('bulk-insert/', views.bulk_insert_student_admission, name='bulk_insert_student_admission'),
    path('student_updatefee/',views.student_updatefee,name="student_updatefee"),
    path("edit_fee_view/<int:id>/", views.edit_fee_view, name="edit_fee_view"),
    path("update_fee_view/<int:id>/", views.update_fee_view, name="update_fee_view"),
    path("student_fee_status/",views.student_fee_status,name="student_fee_status"),
    path("student_fee_view/<int:id>/",views.student_fee_view,name="student_fee_view"),
    path("studentfee_download_receipt/",views.studentfee_download_receipt,name="studentfee_download_receipt"),
    path("insert_teacher/",views.insert_teacher,name="insert_teacher"),
    path("assign_teacher_to_class/",views.assign_teacher_to_class,name="assign_teacher_to_class") ,

    #=============================Teachers ========================


    path('teachers_view/',views.teachers_view,name="teachers_view"),
    path('edit_teacher/<int:id>/',views.edit_teacher,name="edit_teacher"),
    path('update_teacher/<int:id>/',views.update_teacher,name="update_teacher"),
    path('delete_teacher/<int:id>/',views.delete_teacher,name="delete_teacher"),

    path('student_family_details/', views.student_family_details, name="student_family_details"),
    path('student_transport_details/', views.student_transport_details, name="student_transport_details"),
    path('student_fee_management/',views.student_fee_management, name="student_fee_management"),

    path('save-marks/', views.save_student_marks, name='save_student_marks'),
    #============================================================================================
    path('add_class/', views.add_class, name='add_class'),
    path('add_section/', views.add_section, name='add_section'),
    path('add_subject/', views.add_subject, name='add_subject'),
    path('add_fee/', views.add_fee, name='add_fee'),
    path('class-section/', views.class_section_view, name='class_section'),
    path('get-sections-and-fee/', views.get_sections_and_fee, name='get_sections_and_fee'),
    path('save-fee-record/', views.save_fee_record, name='save_fee_record'),
    path('get_sections/', views.get_sections, name='get_sections'),
    path('get_fee_amount/', views.get_fee_amount, name='get_fee_amount'),
    path('class_selection_view/', views.class_selection_view, name='class_selection_view'),
    path('assign_teacher/', views.assign_teacher, name="assign_teacher"),
    path('get_sections_and_subjects/',views.get_sections_and_subjects,name="get_sections_and_subjects"),
    path('insert_exam/',views.insert_exam,name="insert_exam"),
    path('get-sections-subjects/', views.get_sections_subjects, name='get_sections_subjects'),
    path('classteacherstudent/',views.classteacherstudent,name="classteacherstudent"),
    path('save_attendance/', views.save_attendance, name='save_attendance'),
    path('student_attendence_management/', views.student_attendence_management, name='student_attendence_management'),
    path('attendance/', views.student_attendance_management, name='student_attendance_management'),
    path('get_sections1/', views.get_sections1, name='get_sections1'),
    path('std_attendance/', views.std_attendance, name='std_attendance'),
    path('get-subjects-by-section/',  views.get_subjects_by_section, name='get_subjects_by_section'),
    path('export_data/', views.export_data, name='export_data'),
    path("delete-students/", views.delete_students, name="delete_students"),
    path("bulkdataedit/", views.bulkdataedit, name="bulkdataedit"),
    path("students/update/", views.update_student_ajax, name="update_student_ajax"),
    path("deleted_students/", views.deleted_students, name="deleted_students"),
    path("restore_students/", views.restore_students, name="restore_students"),
    path('export_teachers_data/', views.export_teachers_data, name='export_teachers_data'),
    path('bulk_insert_teacher/', views.bulk_insert_teacher, name='bulk_insert_teacher'),
    path('delete_teacher/', views.delete_teacher, name='delete_teacher'),
    path('deleted_teachers/', views.deleted_teachers, name='deleted_teachers'),
    path('restore_teachers/', views.restore_teachers, name='restore_teachers'),
    path('family/', views.family, name='family'),
    path('teacher_marks_feeding/',views.teacher_marks_feeding,name="teacher_marks_feeding"),
    path('view_student_marks/',views.view_student_marks,name="view_student_marks"),
    path('teacher_profile/',views.teacher_profile,name="teacher_profile"),
    path('view_marks_list/',views.view_marks_list,name="view_marks_list"),
    path('student_view_profile/',views.student_view_profile,name="student_view_profile"),
    path('admin_view_student_marks/',views.admin_view_student_marks,name="admin_view_student_marks"),
    path('get_sections2/', views.get_sections2, name='get_sections2'),
    path('teacher_login_list/', views.teacher_login_list, name='teacher_login_list'),
    path('teacher_login_edit/<int:id>/',views.teacher_login_edit,name="teacher_login_edit"),
    path('teacher_update_login/<int:id>/',views.teacher_update_login,name="teacher_update_login"),
    path('student_leave_request/', views.student_leave_request, name='student_leave_request'),
    path('manage_leave_requests/', views.manage_leave_requests, name='manage_leave_requests'),
    path('leave/<int:leave_id>/accept/', views.accept_leave, name='accept_leave'),
    path('leave/<int:leave_id>/reject/', views.reject_leave, name='reject_leave'),
    path('teacher_leave_request/', views.teacher_leave_request, name='teacher_leave_request'),
    path('admin_teacher_leave_requests/', views.admin_teacher_leave_requests, name='admin_teacher_leave_requests'),
    path('admin_approve_teacher_leave/<int:leave_id>/', views.admin_approve_teacher_leave, name='admin_approve_teacher_leave'),
    path('admin_reject_teacher_leave/<int:leave_id>/', views.admin_reject_teacher_leave, name='admin_reject_teacher_leave'),
    path('edit_student_marks/<int:student_id>/<int:exam_id>/', views.edit_student_marks, name='edit_student_marks'),
    path('view_report_card/<int:student_id>/<int:exam_id>/', views.view_report_card, name='view_report_card'),
    path('download_report_card/<int:student_id>/<int:exam_id>/', views.download_report_card, name='download_report_card'),
    path('delete_marks/<int:mark_id>/', views.delete_student_marks, name='delete_student_marks'),
    path('insert_extra_subject_marks/', views.insert_extra_subject_marks, name='insert_extra_subject_marks'),
    path('get_subjects_and_term_marks/', views.get_subjects_and_term_marks, name='get_subjects_and_term_marks'),
    path('admin_student_credentials/', views.admin_student_credentials, name='admin_student_credentials'),
    path('admin_teacher_credentials/', views.admin_teacher_credentials, name='admin_teacher_credentials'),
    path('create_circular/', views.create_circular, name='create_circular'),
    path('circular_list/', views.circular_list, name='circular_list'),
    path('edit_circular/<int:pk>/', views.edit_circular, name='edit_circular'),
    path('delete_circular/<int:pk>/', views.delete_circular, name='delete_circular'),
    path('student_circular/', views.student_circular, name='student_circular'),
    path('teacher_circular/', views.teacher_circular, name='teacher_circular'),
    path('class_teachers_list/',views.class_teachers_list,name='class_teachers_list'),
    path('student_fee_details/',views.student_fee_details,name='student_fee_details'),
    #=========================================WEBSITE===========================================

    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('classes/', views.classes, name='classes'),
    path('facility/', views.facility, name='facility'),
    path('team/', views.team, name='team'),
    path('become_teacher/', views.become_teacher, name='become_teacher'),
    path('appointment/', views.appointment, name='appointment'),
    path('testimonial/', views.testimonial, name='testimonial'),
    path('contact/', views.contact, name='contact'),
    path('error_404/', views.error_404, name='error_404'),
    path('student/', views.student, name='student'),
    path('teacher/', views.teacher, name='teacher'),

    #==========================================================
    path('add_school_details/', views.add_school_details, name='add_school_details'),

#==============================================Menu=============================
    path('add_heading/', views.add_heading, name='add_heading'),
    path('add_submenu/', views.add_submenu, name='add_submenu'),
    path('manage_teacher_dashboard/', views.manage_teacher_dashboard, name='manage_teacher_dashboard'),
   
    path("gallery_list/", views.gallery_list, name="gallery_list"),
    path("gallery_detail/<int:album_id>/", views.gallery_detail, name="gallery_detail"),
    path("create_album/", views.create_album, name="create_album"),
    path("upload_image/<int:album_id>/", views.upload_image, name="upload_image"),
    path("event_list/", views.event_list, name="event_list"),
    path("event_detail/<int:event_id>/", views.event_detail, name="event_detail"),
    path("create_event", views.create_event, name="create_event"),
    path("student_gallery_list/", views.student_gallery_list, name="student_gallery_list"),
    path("student_gallery_detail/<int:album_id>/", views.student_gallery_detail, name="student_gallery_detail"),
    path("student_event_list/", views.student_event_list, name="student_event_list"),
    path("student_event_detail/<int:event_id>/", views.student_event_detail, name="student_event_detail"),
    path("teacher_gallery_list/", views.teacher_gallery_list, name="teacher_gallery_list"),
    path("teacher_gallery_detail/<int:album_id>/", views.teacher_gallery_detail, name="teacher_gallery_detail"),
    path("teacher_create_album/", views.teacher_create_album, name="teacher_create_album"),
    path("teacher_upload_image/<int:album_id>/", views.teacher_upload_image, name="teacher_upload_image"),
    path("teacher_event_list/", views.teacher_event_list, name="teacher_event_list"),
    path("teacher_event_detail/<int:event_id>/", views.teacher_event_detail, name="teacher_event_detail"),
    path("teacher_create_event/", views.teacher_create_event, name="teacher_create_event"),
    path("download_images/", views.download_images, name="download_images"),
    path('students_using_transport/', views.students_using_transport, name='students_using_transport'),
    path('students_not_using_transport/', views.students_not_using_transport, name="students_not_using_transport"),
    path('non-teaching-staff_dashboard/', views.non_teaching_staff_dashboard, name='non_teaching_staff_dashboard'),
    path('add_non_teaching_staff/', views.add_non_teaching_staff, name='add_non_teaching_staff'),
    path('non_teaching_staff_list/',views.non_teaching_staff_list,name="non_teaching_staff_list"),
    path('students_using_transport1/', views.students_using_transport1, name='students_using_transport1'),
    path('students_not_using_transport1/', views.students_not_using_transport1, name="students_not_using_transport1"),
    path('add_transport/',views.add_transport,name="add_transport"),
    path('transport_list/',views.transport_list,name="transport_list"),
    path('edit_transport<int:pk>/', views.edit_transport, name='edit_transport'),
    path('delete_transport/<int:pk>/', views.delete_transport, name='delete_transport'),
    path('drivers_list/',views.drivers_list,name="drivers_list"),
    path('edit_driver/<int:pk>/', views.edit_driver, name='edit_driver'),
    path('delete_driver/<int:pk>/', views.delete_driver, name='delete_driver'),
    path('add_driver/', views.add_driver, name='add_driver'),
    path('assign_driver/', views.assign_driver, name='assign_driver'),
    path('admin_transport_list/', views.admin_transport_list, name='admin_transport_list'),
    path('admin_driver_list/', views.admin_driver_list, name='admin_driver_list'),
    path('add_route/', views.add_route, name='add_route'),
    path('route_list/', views.route_list, name='route_list'),
    path('edit_route/<int:pk>/', views.edit_route, name='edit_route'),
    path('delete_route/<int:pk>/', views.delete_route, name='delete_route'),
    path('transport_student_list/', views.transport_student_list, name='transport_student_list'),
    path('export-transport/pdf/', views.export_transport_pdf, name='export_transport_pdf'),
    path('export-transport/excel/', views.export_transport_excel, name='export_transport_excel'),
    path('admin_transport_student_list/', views.admin_transport_student_list, name='admin_transport_student_list'),
    path('admin-export-transport/pdf/', views.admin_export_transport_pdf, name='admin_export_transport_pdf'),
    path('admin_export-transport/excel/', views.admin_export_transport_excel, name='admin_export_transport_excel'),
    path('mark_transport_attendance/', views.mark_transport_attendance, name="mark_transport_attendance"),
    path('view_transport_attendance/', views.view_transport_attendance, name='view_transport_attendance'),
    path('admin_view_transport_attendance/', views.admin_view_transport_attendance, name='admin_view_transport_attendance'),
    path('transport_attendance_summary/', views.transport_attendance_summary,name="transport_attendance_summary"),
    path('admin_transport_attendance_summary/', views.admin_transport_attendance_summary, name="admin_transport_attendance_summary"),
    path('student_attendance_history/',views.student_attendance_history,name="student_attendance_history"),
    path('student_transport_details1/',views.student_transport_details1,name="student_transport_details1"),
    path('report_transport_issue/',views.report_transport_issue,name="report_transport_issue"),
    path('transport_issues/', views.transport_issues, name='transport_issues'),
    path('resolve_transport_issue/<int:issue_id>/', views.resolve_transport_issue, name='resolve_transport_issue'),
    path('admin_transport_issues/', views.admin_transport_issues, name='admin_transport_issues'),
    path('admin_resolve_transport_issue/<int:issue_id>/', views.admin_resolve_transport_issue, name='admin_resolve_transport_issue'),
    path('select_user_to_chat/', views.select_user_to_chat, name='select_user_to_chat'),
    path('chat_with_user/<int:user_id>/', views.chat_with_user, name='chat_with_user'),
    path('inbox/', views.inbox, name='inbox'),
    path('set_typing_status/', views.set_typing_status, name='set_typing_status'),
    path('get_typing_status/<int:user_id>/', views.get_typing_status, name='get_typing_status'),
    path('get-attendance-summary/', views.get_attendance_summary, name='get_attendance_summary'),
    # path('<str:pk>',views.show,name="show"),

    path('upload_class_photo/', views.upload_class_photo, name='upload_class_photo'),
    path('get_sections3/', views.get_sections3, name='get_sections3'),
    path('get-sections4/', views.get_sections4, name='get_sections4'),
    path('admin_generate_reportcard/',views.admin_generate_reportcard,name="admin_generate_reportcard"),
    path('student_report_card/',views.student_report_card,name="student_report_card"),
    path('mark_notifications_read/',views.mark_notifications_read,name="mark_notifications_read"),
    path('lead_sources/', views.lead_sources, name='lead_sources'),
    path('edit_source/edit/<int:pk>/', views.edit_source, name='edit_source'),
    path('delete_source/delete/<int:pk>/', views.delete_source, name='delete_source'),
    path('lead_statuses/', views.lead_statuses, name='lead_statuses'),
    path('edit_status/edit/<int:pk>/', views.edit_status, name='edit_status'),
    path('delete_status/delete/<int:pk>/', views.delete_status, name='delete_status'),
    path('leads_list/', views.leads_list, name='leads_list'),
    path('add_lead/', views.add_lead, name='add_lead'),
    path('view_lead/<int:id>/',views.view_lead,name="view_lead"),
    path('edit_lead/<int:pk>/', views.edit_lead, name='edit_lead'),
    path('transport_fee_view/', views.transport_fee_view, name='transport_fee_view'),
    path('create_timetable/',views.create_timetable,name="create_timetable"),
    path('get_subjects/',views.get_subjects,name="get_subjects"),
    path('get_teachers_by_subject/',views.get_teachers_by_subject,name="get_teachers_by_subject"),
    path('get_timetable_data/',views.get_timetable_data,name="get_timetable_data"),
    path('teacher_timetable/',views.teacher_timetable,name="teacher_timetable"),
    path('student_timetable/',views.student_timetable,name="student_timetable"),
    path('admissions/', views.admissions_view, name='admissions'),
]







if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)